integer1 = int(input("Enter Integer "))
integer2 = int(input("Enter Another Integer "))
integer3 = int(input("Enter 3rd Integer "))
integer4 = int(input("Enter 4th Integer "))
mylist = (integer1, integer2, integer3, integer4)
print(mylist[0])
print(mylist[1])
print(mylist[2])
print(mylist[3])